"use strict";
let guest = ["Sir Zia Khan", "Kamran Khan Tessori", "Miss Hina Naseer"];
console.log(guest);
console.log("I want to invite three more guest.");
guest.unshift("Sir Ameen Alam");
console.log(guest);
guest.splice(2, 0, "Sir Daniyal Nagori");
console.log(guest);
guest.push("Sir M.Qasim");
console.log(guest);
