"use strict";
let game = "circket";
console.log("Is car == circket? I predict true.");
console.log(game == "circket");
let pen = "piano";
console.log("Is pen == piano? I predict true.");
console.log(pen == "piano");
let cloth = "red";
console.log("Is cloth == red? I predict true.");
console.log(cloth == "red");
let message = "yes";
console.log("Is message == yes? I predict true.");
console.log(message == "yes");
let shirt = "black";
console.log("Is shirt == black? I predict true.");
console.log(shirt == "black");
let flower = "rose";
console.log("Is flower == sunflower? I predict false.");
console.log(flower == "sunflower");
let laptop = "dell";
console.log("Is laptop == hp? I predict false.");
console.log(laptop == "hp");
let watch = "silver";
console.log("Is watch == golden? I predict false.");
console.log(watch == "golden");
let country = "pakistan";
console.log("Is country == America? I predict false.");
console.log(country == "america");
let fruit = "mango";
console.log("Is fruit == apple? I predict false.");
console.log(fruit == "apple");
